# Generated by Django 4.1.7 on 2023-10-31 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('cant_cupos', models.IntegerField()),
                ('tipo', models.CharField(choices=[('COMUN', 'Comun'), ('LABORATORIO', 'Laboratorio'), ('MODULO', 'Modulo'), ('OFICINA', 'Oficina')], default='COMUN', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('LICENCIATURA', 'Licenciatura'), ('TECNICATURA', 'Tecnicatura'), ('POSTGRADO', 'Postgrado'), ('MAESTRIA', 'Maestria')], default='LICENCIATURA', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('cant_insc', models.IntegerField()),
                ('requiere_aula_exclusiva', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comision_BH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=9)),
                ('hora_ini', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carrera')),
            ],
        ),
        migrations.AddIndex(
            model_name='herramienta',
            index=models.Index(fields=['id', 'nombre'], name='app_herrami_id_bba871_idx'),
        ),
        migrations.AddField(
            model_name='comision_bh',
            name='comision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comision', to_field='nombre'),
        ),
        migrations.AddField(
            model_name='comision',
            name='comision_compartida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comision'),
        ),
        migrations.AddField(
            model_name='comision',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.materia'),
        ),
        migrations.AddField(
            model_name='comision',
            name='preferencias',
            field=models.ManyToManyField(blank=True, to='app.herramienta'),
        ),
        migrations.AddIndex(
            model_name='carrera',
            index=models.Index(fields=['id', 'nombre'], name='app_carrera_id_a4bb78_idx'),
        ),
        migrations.AddField(
            model_name='aula',
            name='aula_compartida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aula'),
        ),
        migrations.AddField(
            model_name='aula',
            name='herramientas',
            field=models.ManyToManyField(blank=True, to='app.herramienta'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='aula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aula'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='comision_bh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comision_bh'),
        ),
        migrations.AddIndex(
            model_name='materia',
            index=models.Index(fields=['id', 'nombre'], name='app_materia_id_0fd637_idx'),
        ),
        migrations.AddIndex(
            model_name='comision_bh',
            index=models.Index(fields=['id', 'fecha_fin'], name='app_comisio_id_1b84fc_idx'),
        ),
        migrations.AddIndex(
            model_name='comision',
            index=models.Index(fields=['id', 'nombre'], name='app_comisio_id_c13701_idx'),
        ),
        migrations.AddIndex(
            model_name='aula',
            index=models.Index(fields=['id', 'nombre'], name='app_aula_id_04460f_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['comision_bh'], name='app_asignac_comisio_7498c0_idx'),
        ),
    ]
