# Generated by Django 4.1.7 on 2023-11-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='carrera',
        ),
        migrations.AddField(
            model_name='materia',
            name='carrera',
            field=models.ManyToManyField(to='app.carrera'),
        ),
    ]
