# Generated by Django 4.1.7 on 2023-11-02 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_materia_carrera_materia_carrera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='codigo',
        ),
    ]
