# Generated by Django 4.1.7 on 2023-11-03 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_materia_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='codigo',
        ),
    ]
