# Generated by Django 4.1.7 on 2023-11-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_carrera_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='tipo',
            field=models.CharField(choices=[('LICENCIATURA', 'Licenciatura'), ('TECNICATURA', 'Tecnicatura'), ('POSTGRADO', 'Postgrado'), ('MAESTRIA', 'Maestria')], default='LICENCIATURA', max_length=20, null=True),
        ),
    ]
