# Generated by Django 4.1.7 on 2023-11-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_carrera_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comision_bh',
            name='comision',
        ),
        migrations.AddField(
            model_name='comision_bh',
            name='comision_nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
