# Generated by Django 4.1.7 on 2023-11-07 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_comision_bh_comision_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='aula_compartida',
        ),
    ]
