# Generated by Django 4.2.6 on 2023-11-14 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_espacio_aula_alter_asignacion_aula_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacion',
            old_name='aula',
            new_name='espacio_aula',
        ),
    ]
