# Generated by Django 4.2.6 on 2023-11-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_espacio_aula_capacidad_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio_aula',
            name='capacidad_total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
