# Generated by Django 4.2.6 on 2023-11-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_espacio_aula_capacidad_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio_aula',
            name='test',
            field=models.IntegerField(default=0),
        ),
    ]
