# Generated by Django 4.2.6 on 2023-11-14 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_espacio_aula_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espacio_aula',
            name='capacidad_total',
        ),
        migrations.RemoveField(
            model_name='espacio_aula',
            name='test',
        ),
    ]
