# Generated by Django 4.2.6 on 2023-11-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_asignacion_capacidad_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='capacidad_total',
        ),
        migrations.AddField(
            model_name='espacio_aula',
            name='capacidad_total',
            field=models.IntegerField(default=0),
        ),
    ]
