# Generated by Django 4.2.6 on 2023-11-16 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_asignacion_capacidad_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='aula_exclusiva',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.espacio_aula'),
        ),
    ]
