# Generated by Django 4.2.6 on 2023-11-23 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_carrera_aula_exclusiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='aula_exclusiva',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.espacio_aula'),
        ),
    ]
