# Generated by Django 4.2.6 on 2023-11-23 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_comision_aula_exclusiva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comision',
            name='requiere_aula_exclusiva',
        ),
    ]
