# Generated by Django 4.2.6 on 2023-11-23 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_comision_requiere_aula_exclusiva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='aula_exclusiva',
        ),
    ]
