# Generated by Django 4.1.5 on 2024-10-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_carrera_aula_exclusiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='real',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
