# Generated by Django 4.1.5 on 2025-03-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_asignacion_real'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aula',
            old_name='cant_cupos',
            new_name='capacidad',
        ),
        migrations.RemoveField(
            model_name='espacio_aula',
            name='aula',
        ),
        migrations.RemoveField(
            model_name='espacio_aula',
            name='capacidad_total',
        ),
        migrations.AddField(
            model_name='aula',
            name='aulas_cercanas',
            field=models.ManyToManyField(blank=True, to='app.aula'),
        ),
        migrations.AddField(
            model_name='espacio_aula',
            name='aulas',
            field=models.ManyToManyField(related_name='grupos_extensibles', to='app.aula'),
        ),
        migrations.AlterField(
            model_name='espacio_aula',
            name='nombre_combinado',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
