# Generated by Django 4.1.5 on 2025-03-14 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_cant_cupos_aula_capacidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='aula_exclusiva',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aula'),
        ),
    ]
