# Generated by Django 4.1.5 on 2025-03-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_comision_aula_exclusiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='aulas_cercanas',
            field=models.ManyToManyField(blank=True, related_name='aulas_adyacentes', to='app.aula'),
        ),
    ]
