# Generated by Django 4.1.5 on 2025-03-15 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_aula_aulas_cercanas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='real',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aula'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='espacio_aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.espacio_aula'),
        ),
    ]
