# Generated by Django 4.1.5 on 2025-03-30 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_asignacion_real_asignacion_aula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='aula_exclusiva',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.espacio_aula'),
        ),
    ]
