# Generated by Django 4.1.5 on 2025-04-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_comision_aula_exclusiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio_aula',
            name='capacidad_total',
            field=models.IntegerField(default=0),
        ),
    ]
