# Generated by Django 4.1.5 on 2025-04-08 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_espacio_aula_capacidad_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='aula',
        ),
        migrations.RemoveField(
            model_name='espacio_aula',
            name='capacidad_total',
        ),
    ]
